### ISSUE TITLE
I'm sorry,there is no forum.

### ISSUE THREAD

**Issue by mysteryzzp** [MoKee/android_packages_apps_Mms#1]
I want to know which project is  android.provider.Telephony.Sms locate?

I am so sorry, but there is no forum. I have no place to post this.

Anyone can help?

**Comment by martincz** [comment]
Look this.
https://github.com/MoKee/android_frameworks_opt_telephony/blob/jb-mr1_mkt/src/java/android/provider/Telephony.java

**Comment by mysteryzzp** [comment]
thanks so much.
